DanielG/urls.py
from django.contrib import admin
from django.urls import path
from .views.home import Index , store
from .views.signup import Signup
from .views.login import Login , logout
from .views.cart import Cart
from .views.checkout import CheckOut
from .views.orders import OrderView
from .middlewares.auth import  auth_middleware

app_name="DanielG"
urlpatterns = [
    path('', Index.as_view(), name='homepage'),
    path('store/', store , name='store'),

    path('signup/', Signup.as_view(), name='signup'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', logout , name='logout'),
    path('cart/', auth_middleware(Cart.as_view()) , name='cart'),
    path('checkout/', CheckOut.as_view() , name='checkout'),
    path('orders/', auth_middleware(OrderView.as_view()), name='orders'),

]

myWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('DanielG.urls', namespace='DanielG')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DanielG/models/customer.py
from django.db import models

class Customer(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField (max_length=50)
    phone = models.CharField(max_length=10)
    email=models.EmailField()
    password = models.CharField(max_length=100)

    #to save the data
    def register(self):
        self.save()


    @staticmethod
    def get_customer_by_email(email):
        try:
            return Customer.objects.get(email= email)
        except:
            return False


    def isExists(self):
        if Customer.objects.filter(email = self.email):
            return True

        return False

DanielG/models/orders.py
from django.db import models
from .product import Products
from .customer import Customer
import datetime


class Order(models.Model):
    product = models.ForeignKey(Products,
                                on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer,
                                 on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    price = models.IntegerField()
    address = models.CharField (max_length=50, default='', blank=True)
    phone = models.CharField (max_length=50, default='', blank=True)
    date = models.DateField (default=datetime.datetime.today)
    status = models.BooleanField (default=False)

    def placeOrder(self):
        self.save()

    @staticmethod
    def get_orders_by_customer(customer_id):
        return Order.objects.filter(customer=customer_id).order_by('-date')

DanielG/models/product.py
from django.db import models

class Products(models.Model):
    name = models.CharField(max_length=60)
    price= models.IntegerField(default=0)
    description= models.CharField(max_length=250, default='', blank=True, null= True)
    image= models.ImageField(upload_to='static/assets/')

    @staticmethod
    def get_products_by_id(ids):
        return Products.objects.filter (id__in=ids)
    @staticmethod
    def get_all_products():
        return Products.objects.all()

    @staticmethod
    def get_all_products_by_categoryid(category_id):
        if category_id:
            return Products.objects.filter (category=category_id)
        else:
            return Products.get_all_products()

DanielG/views/cart.py
from django.shortcuts import render , redirect

from django.contrib.auth.hashers import  check_password
from DanielG.models.customer import Customer
from django.views import  View
from DanielG.models.product import Products

class Cart(View):
    def get(self , request):
        ids = list(request.session.get('cart').keys())
        products = Products.get_products_by_id(ids)
        print(products)
        return render(request , 'cart.html' , {'products' : products} )

DanielG/views/checkout.py
from django.shortcuts import render, redirect

from django.contrib.auth.hashers import check_password
from DanielG.models.customer import Customer
from django.views import View

from DanielG.models.product import Products
from DanielG.models.orders import Order


class CheckOut(View):
    def post(self, request):
        address = request.POST.get('address')
        phone = request.POST.get('phone')
        customer = request.session.get('customer')
        cart = request.session.get('cart')
        products = Products.get_products_by_id(list(cart.keys()))
        print(address, phone, customer, cart, products)

        for product in products:
            print(cart.get(str(product.id)))
            order = Order(customer=Customer(id=customer),
                          product=product,
                          price=product.price,
                          address=address,
                          phone=phone,
                          quantity=cart.get(str(product.id)))
            order.save()
        request.session['cart'] = {}

        return redirect('DanielG:cart')

DanielG/views/home.py
from django.shortcuts import render , redirect , HttpResponseRedirect
from DanielG.models.product import Products
from django.views import View


# Create your views here.
class Index(View):

    def post(self , request):
        product = request.POST.get('product')
        remove = request.POST.get('remove')
        cart = request.session.get('cart')
        if cart:
            quantity = cart.get(product)
            if quantity:
                if remove:
                    if quantity<=1:
                        cart.pop(product)
                    else:
                        cart[product]  = quantity-1
                else:
                    cart[product]  = quantity+1

            else:
                cart[product] = 1
        else:
            cart = {}
            cart[product] = 1

        request.session['cart'] = cart
        print('cart' , request.session['cart'])
        return redirect('DanielG:homepage')



    def get(self , request):
        # print()
        return HttpResponseRedirect(f'/store{request.get_full_path()[1:]}')

def store(request):
    cart = request.session.get('cart')
    if not cart:
        request.session['cart'] = {}
    products = None
    categoryID = request.GET.get('category')
    if categoryID:
        products = Products.get_all_products_by_categoryid(categoryID)
    else:
        products = Products.get_all_products()

    data = {}
    data['products'] = products

    print('you are : ', request.session.get('email'))
    return render(request, 'index.html', data)

DanielG/views/login.py
from django.shortcuts import render , redirect , HttpResponseRedirect
from django.contrib.auth.hashers import  check_password
from DanielG.models.customer import Customer
from django.views import View


class Login(View):
    return_url = None

    def get(self, request):
        Login.return_url = request.GET.get ('return_url')
        return render (request, 'login.html')

    def post(self, request):
        email = request.POST.get ('email')
        password = request.POST.get ('password')
        customer = Customer.get_customer_by_email (email)
        error_message = None
        if customer:
            flag = check_password (password, customer.password)
            if flag:
                request.session['customer'] = customer.id

                if Login.return_url:
                    return HttpResponseRedirect (Login.return_url)
                else:
                    Login.return_url = None
                    return redirect ('DanielG:homepage')
            else:
                error_message = 'Invalid !!'
        else:
            error_message = 'Invalid !!'

        print (email, password)
        return render (request, 'login.html', {'error': error_message})

def logout(request):
    request.session.clear()
    return redirect('DanielG:login')

DanielG/views/orders.py
from django.shortcuts import render, redirect
from django.contrib.auth.hashers import check_password
from DanielG.models.customer import Customer
from django.views import View
from DanielG.models.product import Products
from DanielG.models.orders import Order
from DanielG.middlewares.auth import auth_middleware

class OrderView(View):


    def get(self , request ):
        customer = request.session.get('customer')
        orders = Order.get_orders_by_customer(customer)
        print(orders)
        return render(request , 'orders.html'  , {'orders' : orders})

DanielG/views/signup.py
from django.shortcuts import render, redirect
from django.contrib.auth.hashers import make_password
from DanielG.models.customer import Customer
from django.views import View


class Signup (View):
    def get(self, request):
        return render (request, 'signup.html')

    def post(self, request):
        postData = request.POST
        first_name = postData.get ('firstname')
        last_name = postData.get ('lastname')
        phone = postData.get ('phone')
        email = postData.get ('email')
        password = postData.get ('password')
        # validation
        value = {
            'first_name': first_name,
            'last_name': last_name,
            'phone': phone,
            'email': email
        }
        error_message = None

        customer = Customer (first_name=first_name,
                             last_name=last_name,
                             phone=phone,
                             email=email,
                             password=password)
        error_message = self.validateCustomer (customer)

        if not error_message:
            print (first_name, last_name, phone, email, password)
            customer.password = make_password (customer.password)
            customer.register ()
            return redirect ('DanielG:homepage')
        else:
            data = {
                'error': error_message,
                'values': value
            }
            return render (request, 'signup.html', data)

    def validateCustomer(self, customer):
        error_message = None
        if (not customer.first_name):
            error_message = "Please Enter your First Name !!"
        elif len (customer.first_name) < 3:
            error_message = 'First Name must be 3 char long or more'
        elif not customer.last_name:
            error_message = 'Please Enter your Last Name'
        elif len (customer.last_name) < 3:
            error_message = 'Last Name must be 3 char long or more'
        elif not customer.phone:
            error_message = 'Enter your Phone Number'
        elif len (customer.phone) < 10:
            error_message = 'Phone Number must be 10 char Long'
        elif len (customer.password) < 5:
            error_message = 'Password must be 5 char long'
        elif len (customer.email) < 5:
            error_message = 'Email must be 5 char long'
        elif customer.isExists ():
            error_message = 'Email Address Already Registered..'
        # saving

        return error_message

DanielG/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Daniel Gallego</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        .navbar {
            font-size: 20px;
        }

        .navbar .hover:hover {
            background-color: #ddd;
            color: black;
        }
        .navbar a.active {
            background-color: #04AA6D;
            color: white;
        }

        .sticky {
            position: fixed;
            top: 0;
            width: 100%;
        }

        .sticky + .content {
            padding-top: 60px;
        }    

        .header h1{
            font-size: 80px;
        }

        .header p{
            font-size: 18px;
        }

        .container img {
            width: 100%;
            height: auto;
            opacity: 1;
            transition: .5s ease;
            backface-visibility: hidden;
        }

        .container {
            position: relative;
            width: 100%;
            max-width: 800px;
        }



        footer {
            text-align: center;
            padding: 5px;
            background-color: lightgray;
        }
    </style>
</head>

<body style="max-width:1555px; background-color: rgb(240, 229, 229);">
<div class="jumbotron text-center header" style="margin-bottom: 0; height: 200%;">
    <div class="row">
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 col-xl-4" style="width: 20%; height: 20%;">
            <img src="{% static 'assets/JEANS.png' %}" alt="Daniel Gallego JEANS" style="width: 80%; height :80%; padding-top: -10px; float: left;">
        </div>
        <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8 col-xl-8">
            <h1 style="font-size: 8vw;">Daniel Gallego</h1>
            <p style="font-size: 2vw;">South Africa's Finest Jeans</p>
        </div>
    </div>
</div>

 <nav class="navbar navbar-expand-md bg-dark navbar-dark sticky-top" id="navbar">
    <!-- Brand -->
    <a class="navbar-brand" href="{% url 'DanielG:store'%}">Daniel Gallego</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <!-- Links -->
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav mr-auto">
        <li>
        <form class="navbar-form navbar-left" action="/action_page.php">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search" name="search">
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <i class="glyphicon glyphicon-search"></i>
                        </button>
                    </div>
                </div>
        </form>
        </li>
    </ul>
        <!-- Dropdown -->
        <ul class="navbar-nav my-2">
            <li class="nav-item active ml-auto">
            <a class="nav-link" href="{% url 'DanielG:cart'%}" style="float:right">Cart 
              <span class="badge badge-success">{{request.session.cart.keys|length}}</span>
              <span class="sr-only">(current)</span></a>
            </li>
  
        {% if request.session.customer %}
          
          <li class="nav-item active  ml-auto">
            <a class="nav-link" href="{% url 'DanielG:orders'%}">Orders<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active  ml-auto">
            <a class="nav-link" href="{% url 'DanielG:logout'%}">Logout<span class="sr-only">(current)</span></a>
          </li>
          {% else %}
         
          <li class="nav-item active  ml-auto">
            <a class="nav-link" href="{% url 'DanielG:signup'%}">Signup<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active  ml-auto">
            <a class="nav-link" href="{% url 'DanielG:login'%}">Login<span class="sr-only">(current)</span></a>
          </li>
          {% endif %}

        </ul>
    </div>
  </nav>

  {% block content %}{% endblock %}

<script>
    window.onscroll = function() {myFunction()};
    
    var navbar = document.getElementById("navbar");
    var sticky = navbar.offsetTop;
    
    function myFunction() {
      if (window.pageYOffset >= sticky) {
        navbar.classList.add("sticky")
      } else {
        navbar.classList.remove("sticky");
      }
    }
    </script>
    
</body>
</html>

DanielG/templates/cart.html
{% extends 'base.html' %}

<style>
.container {
  position: relative;
  width: 100%;
  max-width: 800px;
  padding :15px
}
</style>
{% block content %}
{% load cart %}
{% load custom_filter %}
<div class="container">
   <div class="border rounded p-4 m-4">
        <p class="display-4 pl-4 ml-4 btn btn-success rounded-pill">Your Cart</p>
        <hr>
        <table class="table">
            <thead>
                <tr>
                    <th>Sno.</th>
                    <th>Image</th>
                    <th>Product</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                
                {% for product in products %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td><img style="height: 80px;" class="rounded-circle" src="{{product.image.url}}" alt=""></td>
                    <td>{{product.name}}</td>
                    <td>{{product.price|currency}}</td>
                    <td>{{product|cart_quantity:request.session.cart}}</td>
                    <td>{{product|price_total:request.session.cart|currency}}</td>
                </tr>

                {% endfor %}
               
            </tbody>

            <tfoot>
                <tr>
                    <th colspan="4"></th>
                    <th class="" colspan="">Total</th>
                    <th>{{products|total_cart_price:request.session.cart|currency}}</th>
                </tr>
            </tfoot>
        </table>
        <hr>
        <div class="m-3 p-3">
            <a href="#" data-toggle="modal" data-target="#exampleModal" class="btn btn-outline-success border rounded  col-lg-3 float-right">Check out</a>
        </div>
   </div>
</div>


<!-- modal -->

  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">
              Check Out Form
          </h5>
          <hr>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="m-2 p-3">
            <form action="{% url 'DanielG:checkout' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                  <label for="">Address</label>
                  <input type="text" name="address" id="" class="form-control" placeholder="" aria-describedby="helpId">
                  
                </div>
                <div class="form-group">
                    <label for="">Phone</label>
                    <input type="text" name="phone" id="" class="form-control" placeholder="" aria-describedby="helpId">
                  </div>

                  <input type="submit" class="btn float-right btn-outline-success col-lg-6" value="Check out">
            </form>
          </div>
        </div>
        
      </div>
    </div>
  </div>



{% endblock %}

DanielG/templates/index.html
{% extends 'base.html' %}

{% block content %}

{% load cart %}
{% load custom_filter %}
<!-- body -->
<style>
	.container img {
		width: 100%;
		height: auto;
		opacity: 1;
		transition: .5s ease;
		backface-visibility: hidden;
	}
</style>
<div class="container-fluid">
    <p style=" padding: 6px; padding-bottom: 8px;"> 10 items</p>
    <div class="row">
		{% for product in products %}
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-3 col-xl-3" id={{product.id}}>
            <div class="container">
                <img class="img img-responsive" src="{{product.image.url}}" style="width:100%; height: auto;">
				<div class="card-body">
					<p class="card-title">{{product.name}}</p>
					<p class="card-text"><b>{{product.price|currency}}</b></p>
					<!-- {{product | is_in_cart:request.session.cart }} -->
				</div>

				<div class="card-footer p-0 no-gutters">

					{% if product|is_in_cart:request.session.cart %}
					<div class="row no-gutters">
						<form action="/#{{product.id}}" class="col-2 " method="post">
							{% csrf_token %}
							<input hidden type="text" name='product' value='{{product.id}}'>
							<input hidden type="text" name='remove' value='True'>
							<input type="submit" value=" - " class="btn btn-block btn-success border-right">
						</form>
						<div class="text-center col btn btn-success">{{product|cart_quantity:request.session.cart}} in Cart</div>
						<form action="/#{{product.id}}" class="col-2 " method="post">
							{% csrf_token %}
							<input hidden type="text" name='product' value='{{product.id}}'>
							<input type="submit" value=" + " class="btn btn-block btn-success border-left">
						</form>
					</div>
					{% else %}
					<form action="/#{{product.id}}" method="POST" class="btn-block">
						{% csrf_token %}
						<input hidden type="text" name='product' value='{{product.id}}'>
						<input type="submit" class="float-right btn btn-success form-control"
							value="Add To Cart">
					</form>
					{% endif %}

				</div>
            </div>
            
        </div>
		{% endfor %}
	</div>    
</div>



{% endblock %}

DanielG/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
    .container {
        position: relative;
        width: 100%;
        max-width: 800px;
        padding :15px
    }
</style>
<div class="container">
    <div class="p-3 m-3">
        <div class="col-lg-5 rounded mx-auto border pt-4">
            <div class="text-center col">
            
                <img src="{% static 'assets/JEANS.png' %}" alt=""
                class="" style="height: 150px;">
            <hr>
            </div>
            <h3 class="alert alert-light rounded-pill" style="text-align:center" >Login</h3>
            <form action="{% url 'DanielG:login'%}" method="POST">
                
                {% csrf_token %}

                {% if error%}
                <div class="alert alert-danger" role="alert">
                    {{error}}
                </div>
                {% endif %}

        

                <!-- email -->
                <div class="form-group">
                    <label for="">Email</label>
                    <input required type="email" name="email" id=""
                    value="{{values.email}}" 
                    class=" form-control-sm form-control" placeholder="abc@gmail.com">
                </div>


                <!-- password -->
                <div class="form-group">
                    <label for="">Password</label>
                    <input type="password" 
                    name="password" 
                    id=""
                     class="form-control form-control-sm" >
                </div>

                <!--Checkme button-->
            <div class="mb-3 form-check">
                    <input type="checkbox" class="form-check-input" id="exampleCheck1">
                    <label class="form-check-label d-grid gap-2" for="exampleCheck1">Check me out</label>
                </div>
                <hr>
                <button type="submit" class="btn btn-sm btn-success col-lg-12">Login</button>


                
            </form>
        </div>
    </div>
</div>

{% endblock %}

DanielG/templates/orders.html
{% extends 'base.html' %}


{% block content %}
{% load cart %}
{% load custom_filter %}
<div class="container">
   <div class="border rounded p-4 m-4">
        <p class="display-4 pl-4 ml-4">Your Orders</p>
        <hr>
        <table class="table">
            <thead>
                <tr>
                    <th>Sno.</th>
                    <th>Image</th>
                    <th>Product</th>
                    <th>Date</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                
                {% for order in orders %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td><img style="height: 80px;" class="rounded-circle" src="{{order.product.image.url}}" alt=""></td>
                    <td>{{order.product.name}}</td>
                    <td>{{order.date}}</td>
                    <td>{{order.price|currency}}</td>
                    <td>{{order.quantity}}</td>
                    <td>{{order.quantity|multiply:order.price|currency}}</td>
                    {% if order.status %}
                    <td><small class="badge badge-success">Completed</small></td>
                    {%else%}
                    <td><small class="badge badge-warning">Pending</small></td>
                    {% endif %}
                </tr>

                {% endfor %}
               
            </tbody>

        </table>
       
   </div>
</div>





{% endblock %}

DanielG/templates/search.html
{% extends 'base.html' %}
{% block title %} Search {% endblock title %}
{% block content %}

{% load cart %}
{% load custom_filter %}
<!-- body -->
<div class="container-fluid mt-3">
	<div class="row">


		<!-- filter -->
		<!-- all products -->
		<div id='products' class="col-lg-9 mx-auto">
			<div class="row mx-auto">
				{% for product in products %}
				<div class="card mx-auto mb-3" id={{product.id}} style="width: 18rem;">
					<img class="card-img-top" src="{{product.image.url}}" alt="Card image cap">
					<div class="card-body">
						<p class="card-title">{{product.name}}</p>
						<p class="card-text"><b>{{product.price|currency}}</b></p>
						<!-- {{product | is_in_cart:request.session.cart }} -->
					</div>

					<div class="card-footer p-0 no-gutters">

						{% if product|is_in_cart:request.session.cart %}
						<div class="row no-gutters">
							<form action="/#{{product.id}}" class="col-2 " method="post">
								{% csrf_token %}
								<input hidden type="text" name='product' value='{{product.id}}'>
								<input hidden type="text" name='remove' value='True'>
								<input type="submit" value=" - " class="btn btn-block btn-success border-right">
							</form>
							<div class="text-center col btn btn-success">{{product|cart_quantity:request.session.cart}} in Cart</div>
							<form action="/#{{product.id}}" class="col-2 " method="post">
								{% csrf_token %}
								<input hidden type="text" name='product' value='{{product.id}}'>
								<input type="submit" value=" + " class="btn btn-block btn-success border-left">
							</form>
						</div>
						{% else %}
						<form action="/#{{product.id}}" method="POST" class="btn-block">
							{% csrf_token %}
							<input hidden type="text" name='product' value='{{product.id}}'>
							<input type="submit" class="float-right btn btn-success form-control"
								value="Add To Cart">
						</form>
						{% endif %}

					</div>

				</div>
				{% endfor %}
			</div>
		</div>
	</div>
</div>



{% endblock %}

DanielG/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
    .container {
        position: relative;
        width: 100%;
        max-width: 800px;
        padding: 15px;
    }
</style>

<div class="container mt-4">
    
    <div class="p-3 m-3">

        
        <div class="col-lg-5 rounded mx-auto border pt-4">
            <div class="text-center col">
            
                <img
                src="{% static 'assets/JEANS.png' %}" alt=""
                class="" style="height: 150px;">
            <!-- <hr> -->
            <hr>
            </div>
            <h3 class="alert alert-success rounded-pill" style="text-align:center">Create an Account</h3>
            <form action="{% url 'DanielG:signup'%}" method="POST">
                
                {% csrf_token %}

                {% if error%}
                <div class="alert alert-danger" role="alert">
                    {{error}}
                </div>
                {% endif %}
                <!-- firstname -->
                <div class="form-group">
                    <label for="">First Name</label>
                    <input type="text" name="firstname"
                     id="" value="{{values.first_name}}" class="form-control form-control-sm" 
                     placeholder="">
                </div>

                <!-- last name -->
                <div class="form-group">
                    <label for="">Last Name</label>
                    <input type="text" name="lastname" 
                    id="" value="{{values.last_name}}" class="form-control form-control-sm"
                    >
                </div>

                <!-- phone -->
                <div class="form-group">
                    <label for="">Phone</label>
                    <input type="text" name="phone" 
                    id="" class="form-control form-control-sm"
                    value="{{values.phone}}"
                    placeholder="9876543210"
                    >
                </div>
                <!-- email -->
                <div class="form-group">
                    <label for="">Email</label>
                    <input required type="email" name="email" id=""
                    value="{{values.email}}" 
                    class=" form-control-sm form-control" placeholder="abc@gmail.com">
                </div>


                <!-- password -->
                <div class="form-group">
                    <label for="">Password</label>
                    <input type="password" 
                    name="password" 
                    id=""
                     class="form-control form-control-sm">
                </div>

                <!--Checkme button-->
                <div class="mb-3 form-check">
                    <input type="checkbox" class="form-check-input" id="exampleCheck1">
                    <label class="form-check-label d-grid gap-2" for="exampleCheck1">Check me out</label>
                </div>
                <hr>
                <button type="submit" class="btn btn-sm btn-success col-lg-12">Create an account</button>

            </form>
        </div>
    </div>
</div>

{% endblock %}